### ISSUE TITLE
can someone share pose pre trained model

### ISSUE THREAD

**Issue by akkinenic** [NVlabs/few-shot-vid2vid#56] opened 2020-06-18 00:10 UTC
We would gladly appreciate your help. We are students from UC Berkeley and working on something similar for our project. 

The pose pre-trained model really helps our project. 

Can you please share. My email is kakkineni@berkeley.edu

**Comment by tcwang0509** [comment] 2020-12-11 03:24
Duplicate of #22

**Closed as completed by tcwang0509** 2020-12-11 03:24 UTC
