### ISSUE TITLE
"Talking Head" pretrained weights request

### ISSUE THREAD

**Issue by nikitml** [NVlabs/few-shot-vid2vid#71] opened 2020-09-08 11:44 UTC
Hi, could someone please share the link to get the weights for the talking head model. Here's my [university email](mailto:n.lozhnikov@innopolis.ru). I'd be very grateful to use this model in my CNN course.

**Comment by tcwang0509** [comment] 2020-12-11 03:23
Duplicate of #22

**Closed as completed by tcwang0509** 2020-12-11 03:23 UTC
