### ISSUE TITLE
"dance" and "talking head" pretrained model requests

### ISSUE THREAD

**Issue by SeongwoongCho** [NVlabs/few-shot-vid2vid#72] opened 2020-09-13 07:46 UTC
is there someone can share the pretrained model of "dance" and "talking head" ? 

I really need it for my undergraduate lecture. thanks.

seongwoongjo@kaist.ac.kr

**Comment by tcwang0509** [comment] 2020-12-11 03:22
Duplicate of #22

**Closed as completed by tcwang0509** 2020-12-11 03:22 UTC
